title: Plant three trees
emoji: ðŸ‚
description: >
  Mapping a tree is not just placing a _natural=tree_ node. You have to specify its type.
  Please read wiki pages on [https://whatever.com leaf_type]
  and [https://www leaf_cycle], and then add 3 trees near your home or somewhere
  familiar to you using these tags.
test:
  created_3_nodes: ["natural=tree", "leaf_type=*", "leaf_cycle=*"]
