title: Fix a subway
emoji: ðŸš‡
description: |-
  For this you need to know the [https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping Public Transport v2 schema].
  Head to the [https://osmz.ru/subways/ Subway Validator] and pick a city with an error in the subway.
  It should involve modifying a subway route. Fix it â€” and you may go, or continue tidying up the network.
test:
  modified_relation: ["type=route", "route=subway"]
