ja:
  bridge:
    description: 郊外にざっくりと描かれた多くの道路は、水路や川との交差を処理しわすれていることがしばしばあります。そうした場所を見つけ、道路ウェイを分割して橋を適切に追加しましょう。
    title: 橋を描こう
  stream:
    description: 大きな河川は既に世界中で、その多くが描かれています。ですが、小さな川はまだ無数に存在します。どこか小川が流れている場所を探して、マップしてみましょう。水路ではありませんよ。
    title: 小さな川を描こう
  postcode:
    description: ロシアやアメリカなどいくつかの国では、郵便番号コードが公開され、利用可能な状態になっています。そうではない国でも、お店のウェブサイトなどの間接的な情報源から郵便番号を推測したり、単純に調査したりすることができるはずです。どこかの建物の郵便番号を探して、マップしましょう。
    title: 郵便番号の追加
  bench:
    description: 最近、公園を歩いたときにベンチを見かけませんでしたか？ その場所を思い出してみましょう。今日のタスクはベンチを1つ描くことです。
    title: ベンチを描こう
  turn_restriction:
    description: MapillaryやOSMで使える情報源を参照して、まだ入力されていない方向展開制限（右折禁止・左折禁止）を見つけてみましょう。小さな街のほうがよいかもしれません。展開制限を入力してみましょう。
    title: 方向展開制限の入力
  lit:
    description: 街灯の明かりに包まれた街はいつもより美しく見えます。道路に対して"lit=yes"や"lit=no"を入力し、少し時間が経ってから[http://product.itoworld.com/map/69 この地図で]街が色づいているのを見てみましょう。
    title: 道路に明かりを灯して
  osmand:
    description: '[https://play.google.com/store/apps/details?id=net.osmand OsmAnd] はAndroid端末でよく使われるOpenStreetMapアプリのひとつです。細かい箇所までカスタマイズできるのが特徴ですが、人によっては複雑すぎるかもしれません。OsmAndではマップにポイントを投稿することができます。 "OSM Editing"プラグインをインストールして、どこかにポイントを作成しましょう。操作方法については [http://osmand.net/features?id=osm-editing-plugin the documentation] に解説があります。'
    title: OsmAndを使おう
  improve_river:
    description: "ほとんどの大きな河川は既に描かれています。問題は、それらが描かれる際に、画質の悪い衛星写真が利用されている、ということです。いまの私たちならもっと正確に描くことが可能です。JOSMを起動し、河川を選択し、 \"W\"キーを押してウェイの精度を向上させましょう。\"waterway=river\"ウェイに対して、10個以上のノードを追加してください。"
    title: 河川の品質向上
  josm:
    description: "未体験のかたもJOSMをインストールし、JOSMで何かを描いてみましょう。対象は建物がオススメです。\n\nマップデータをダウンロードし、背景となる写真レイヤを追加し、\"A\"キーを押して建物のどこかの角をクリックします。次に、その近くの別の角をダブルクリックし、線を作ります。その後、”X”キーを押して、いま描いた線を四角形にします。最後に、\"Alt+A\"を押して、\"building=yes\"タグを追加し、変更点をアップロードしましょう。"
    title: JOSMを使ってみよう
  fix:
    description: '変更セットのコメントは本来非常に重要です。ですが、今日のあなたには関係ありません。地図の編集を行い、コメントとして単に "fix" とだけ入力しましょう。入力するのはこの3文字だけで、それ以上入れてはいけません。'
    title: 小さな変更
  gomap:
    description: 'Androidプラットフォームには多くのOSMエディタが用意されていますが、iOSではまだ少ないのが現状です。そのなかで最も使いやすいアプリは  [https://itunes.apple.com/app/id592990211 Go Map!!] （ビックリマークまでを含む）なのですが、更新が2015年で止まっています。ともあれ、少なくとも動作はします。このアプリを使って編集をしてみましょう。'
    title: Go Map!!!
  giveway:
    description: OSMでは、三角形の "give way （ゆずれ）" 標識をマップするための特別なタグが用意されています。それがまさしく[https://wiki.openstreetmap.org/wiki/Tag:highway%3Dgive_way highway=give_way]タグです。Mapillaryや自分の記憶を頼りにこの標識を探して、道路のライン上にノードを入力し、このタグをつけましょう。また、メインの道路のほうには priority_roadタグをつけましょう。
    title: Give Way（ゆずれ）
  note:
    description: OSMウェブサイトで地図メモ（notes）機能を有効化して、対応可能なメモを解決済みにしましょう。
    title: 地図メモ (note) の解決
  around_the_world:
    description: 広大な範囲を選択して変更セットを作ってみましょう。例えば[https://www.openstreetmap.org/#map=5/-48.487/-69.895 チリ南部]や、[https://www.openstreetmap.org/#map=6/55.912/159.335 カムチャッカ半島]などです。
    title: 5分で巡る世界旅行
  highway:
    description: 道路は、OpenStreetMapに参加するひとの多くがはじめて地図に描く地物です。近くにある描かれていない道路を探して、描いてみましょう。
    title: 道路を描こう
  subway:
    description: このタスクのためには[https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping Public Transport v2（公共交通機関v2）スキーマ]を理解する必要があります。[https://osmz.ru/subways/ Subway Validator]を表示して、地下鉄の構成にエラーのある都市を選んでください。地下鉄の経路を修正する必要があるはずです。エラーを修正し、ネットワークを正しい状態に整備してください。
    title: 地下鉄の修正
  buildings:
    description: 場所はどこでもよいので、建物を20個描きましょう。お好みのエディタを起動し、まだあまり描かれていない郊外や工業地区を探して建物を描きましょう。
    title: 建物を20個描こう
  lanes:
    description: '"lanes"タグが付与されていない道路を見つけましょう。その地域の詳細な航空写真を参照して、道路に対して車線の数を入力します。'
    title: 車線を数えよ
  streetcomplete:
    description: iPhoneのかた、本日は残念でした。Androidのかたは[https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete StreetComplete]をインストールして、タスクをいくつかこなしてみましょう。1つ1つのタスクは数秒で終わります。
    title: StreetCompleteをつかってみよう
  leaf_types:
    description: 樹木のマッピングは単に''natural=tree''ノードを入力するだけではありません。樹木のタイプを指定することだってできます。OSM Wikiの[https://wiki.openstreetmap.org/wiki/Key:leaf_type leaf_type]ページや [https://wiki.openstreetmap.org/wiki/Key:leaf_cycle leaf_cycle]ページを参照して、家の近所など見知った場所にある木を2本、OSMに入力してみましょう。
    title: 樹木を2本追加
  waste_basket:
    description: "バス停の近くや建物の入口など、街を歩いていると、多くのゴミ箱を目にします。その場所を思い出して、''amenity=waste_basket''をマップしましょう。"
    title: ゴミ箱
  tiger:
    description: '[https://wiki.openstreetmap.org/wiki/TIGER TIGER]はアメリカを対象として公開されている道路データセットです。2005年にインポートされましたが、作業はまだ完璧ではありません。tiger:reviewed=noタグがついた道路を3つ以上探し、道路のクラスを正しく修正してからtiger:reviewed=noタグを削除しましょう。'
    title: Tigerの修正
  tracks:
    description: 農道（track）は、その先に農場や森林が続いています。道路のタグは[https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack highway=track]で、追加情報として1 (状態がよい) から5 (悪い) を意味する''tracktype=gradeN''タグをつけることができます。野原や森林の中にある農道を新しく2-3kmほど描いてみましょう。
    title: 農道を描こう
  hot_task:
    description: '[https://tasks.hotosm.org/ HOT Tasking Manager]を開き、現在アクティブなタスクを1つ選びます。そこで黄色の四角形をランダムに1つ選び、内容のチェックを行ってください。初心者マッパーが建物を適当に描いていないかなどをしっかり確認し、必要に応じて角を直角にしたり形を修正したりしてください。2地域ほどやってみましょう。'
    title: 建物の修正
  lamps:
    description: 窓の外はもう暗いですか？ 道路に街灯が光っているのが見えますか？ その街灯はマップされていますか？ 2つ以上の[https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp highway=street_lamp]タグを入力しましょう。
    title: 街灯の植樹
  coastline:
    description: 海岸線はその多くがはるか昔にインポートされ、もとのデータは低解像度の衛星写真がもとになっています。海岸線の更新を行いましょう。海岸線のラインを構成するノードを10個以上追加してください。
    title: 海岸線の改良
  haiti:
    description: '2010年、ハイチの首都ポルトープランスから10kmの地点で壊滅的な被害をもたらす地震が発生しました。これがHumanitarian Mapping Teamのはじまりで、いまでは街は完全にマップされています。しかしそこから少し離れた場所はどうでしょうか。まだ描かれていないハイチの建物を探し、トレースしてみましょう。'
    title: ハイチを訪問
  railway:
    description: 道路に比べて興味を持たれることの少ない鉄道路線、ですが、重要さは道路に負けません！ 今日は路線情報をマップしましょう。例えば、駅の近くにあるサイドトラックがまだ描けるかもしれません。
    title: 鉄道を描こう
  turnlanes:
    description: '[https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane turn:lanes]の記載に目を通し、車線ありの交差点を高精度な航空写真やMapillaryで探して、交差点の四隅に対してすべて turn lanesタグを入力してみましょう。'
    title: 進行方向つきの車線
  farmland:
    description: 耕作地や牧草地を探し (アメリカ中央部やロシア西側がオススメ) 、それらの場所を[https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfarmland landuse=farmland]タグでマップしましょう。
    title: 農場をマップしよう
  switch:
    description: 2つの線路が交差する場所には、分岐器（railway swith）があるはずです。鉄道駅を探し、線路が接続する場所に対して[https://wiki.openstreetmap.org/wiki/Tag:railway%3Dswitch railway=switch]タグを付与したノードを2つ以上追加しましょう。
    title: 分岐器の追加
  mapsme:
    description: MAPS.MEは単なるナビ付き地図ではありません。地図の編集だって可能です。表示されている施設をクリックするか、メニューにある"地図上に場所を追加"をクリックしてみてください。お試しあれ。
    title: MAPS.MEをつかってみよう
  sidewalk:
    description: ここでの歩道(sidewalk)とは、道路に接して存在する歩行者用の歩道を指します。歩行者用の経路検索のため、歩道が描かれていない道路を探して、その両脇に1本ずつ、 (航空写真を参考に) 歩道を描いて、追加で"footway=sidewalk"タグをつけましょう。横断歩道をウェイとして描く場合は、''highway=footway + footway=crossing'を使ってください。
    title: 歩道を描こう
  delete:
    description: 地図になにかを追加するのは難しくありません。では削除するのはどうでしょう？ 地物を5つ以上削除しましょう。削除するのは、実際に既に無くなっていたり、間違って複数入力されていたりする地物だけにしてください。
    title: 削除！
